export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_CHUNK_MOVIES_SUCCESS = "GET_CHUNK_MOVIES_SUCCESS";
export const RESET_MOVIES_CHUNK = "RESET_MOVIES_CHUNK";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const REFRESH_USER_SUCCESS = "REFRESH_USER_SUCCESS";
export const REQUEST_FAILED = "REQUEST_FAILED";

export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const UNFOLLOW_FRIEND = "UNFOLLOW_FRIEND";
